# Site settings
title: Стандарт информационной открытости НКО
short_title: Стандарт открытости НКО
description: |
    

baseurl: ""
url: "" # the base hostname & protocol for your site

github_username: infoculture
# github_repo: opendatahandbook

# paypal: admin@okfn.org
# contact: http://infoculture.ru

devs:
  -
      name: Павел Медников
      github: Mednikov
  -
      name: Иван Бегтин
      github: ivbeg

# contributors:
#   -
#       name: Rufus Pollock
#       link: http://rufuspollock.org/

supporters:
  -
    name: АНО «Инфокультура»
    logo: ik-logo-hor.png
    footer_logo: ik-logo-hor.png
  -
    name: Форум доноров
    logo: donorsforum.png
    footer_logo: donorsforum.png
    url: http://www.donorsforum.ru/
    url: https://www.infoculture.ru/
  -
    name: Фонд Кудрина по поддержке гражданских инициатив
    logo: kgi.png
    footer_logo: kgi.png
    url: https://komitetgi.ru/


#googleanalytics: UA-XXXXX-X

markdown: kramdown

permalink: pretty

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: page
      section: pages
  -
    scope:
      path: "posts"
    values:
      layout: post
      section: posts


# related_projects:
#   -
#       name: OpenGovernmentData.org
#       link: http://opengovernmentdata.org/
#   -
#       name: The DataHub
#       link: http://datahub.io/
#   -
#       name: DataCatalogs.org
#       link: http://datacatalogs.org/
#   -
#       name: OpenSpending.org
#       link: http://openspending.org/
#   -
#       name: SchoolOfData.org
#       link: http://schoolofdata.org/
#   -
#       name: OpenDefinition.org
#       link: http://opendefinition.org/
#   -
#       name: Introducing Open Data
#       link: http://okfn.org/opendata/
